window.BUSINESS_LESSONS = [
  {
    "day": 1,
    "titleEn": "The Monday Pipeline",
    "titleZh": "周一早高峰的跨国会议",
    "slug": "monday-pipeline",
    "style": "US workplace business English",
    "premise": "a Bay Area tech team handles commute chaos, client pressure, meetings, and a hidden approval problem",
    "words": [
      { "word": "commute", "zh": "通勤", "pos": "business word", "phonetic": "", "globalRank": 4001, "dayRank": 1 },
      { "word": "calendar invite", "zh": "会议邀请", "pos": "business phrase", "phonetic": "", "globalRank": 4002, "dayRank": 2 },
      { "word": "stand-up", "zh": "站会", "pos": "business phrase", "phonetic": "", "globalRank": 4003, "dayRank": 3 },
      { "word": "agenda", "zh": "议程", "pos": "business word", "phonetic": "", "globalRank": 4004, "dayRank": 4 },
      { "word": "action item", "zh": "行动项", "pos": "business phrase", "phonetic": "", "globalRank": 4005, "dayRank": 5 },
      { "word": "deadline", "zh": "截止日期", "pos": "business word", "phonetic": "", "globalRank": 4006, "dayRank": 6 },
      { "word": "blocker", "zh": "阻碍", "pos": "business word", "phonetic": "", "globalRank": 4007, "dayRank": 7 },
      { "word": "stakeholder", "zh": "利益相关者", "pos": "business word", "phonetic": "", "globalRank": 4008, "dayRank": 8 },
      { "word": "alignment", "zh": "对齐共识", "pos": "business word", "phonetic": "", "globalRank": 4009, "dayRank": 9 },
      { "word": "ownership", "zh": "责任归属", "pos": "business word", "phonetic": "", "globalRank": 4010, "dayRank": 10 },
      { "word": "deliverable", "zh": "交付物", "pos": "business word", "phonetic": "", "globalRank": 4011, "dayRank": 11 },
      { "word": "status update", "zh": "状态更新", "pos": "business phrase", "phonetic": "", "globalRank": 4012, "dayRank": 12 },
      { "word": "KPI", "zh": "关键绩效指标", "pos": "business abbreviation", "phonetic": "", "globalRank": 4013, "dayRank": 13 },
      { "word": "OKR", "zh": "目标与关键结果", "pos": "business abbreviation", "phonetic": "", "globalRank": 4014, "dayRank": 14 },
      { "word": "roadmap", "zh": "路线图", "pos": "business word", "phonetic": "", "globalRank": 4015, "dayRank": 15 },
      { "word": "milestone", "zh": "里程碑", "pos": "business word", "phonetic": "", "globalRank": 4016, "dayRank": 16 },
      { "word": "bandwidth", "zh": "可用精力", "pos": "business word", "phonetic": "", "globalRank": 4017, "dayRank": 17 },
      { "word": "priority", "zh": "优先级", "pos": "business word", "phonetic": "", "globalRank": 4018, "dayRank": 18 },
      { "word": "trade-off", "zh": "取舍", "pos": "business word", "phonetic": "", "globalRank": 4019, "dayRank": 19 },
      { "word": "next step", "zh": "下一步", "pos": "business phrase", "phonetic": "", "globalRank": 4020, "dayRank": 20 },
      { "word": "follow-up", "zh": "跟进", "pos": "business word", "phonetic": "", "globalRank": 4021, "dayRank": 21 },
      { "word": "recap", "zh": "总结回顾", "pos": "business word", "phonetic": "", "globalRank": 4022, "dayRank": 22 },
      { "word": "please find attached", "zh": "请查收附件", "pos": "email phrase", "phonetic": "", "globalRank": 4023, "dayRank": 23 },
      { "word": "as discussed", "zh": "如前所述", "pos": "email phrase", "phonetic": "", "globalRank": 4024, "dayRank": 24 },
      { "word": "for your review", "zh": "供你审阅", "pos": "email phrase", "phonetic": "", "globalRank": 4025, "dayRank": 25 },
      { "word": "draft", "zh": "草稿", "pos": "business word", "phonetic": "", "globalRank": 4026, "dayRank": 26 },
      { "word": "proposal", "zh": "提案", "pos": "business word", "phonetic": "", "globalRank": 4027, "dayRank": 27 },
      { "word": "scope", "zh": "范围", "pos": "business word", "phonetic": "", "globalRank": 4028, "dayRank": 28 },
      { "word": "timeline", "zh": "时间线", "pos": "business word", "phonetic": "", "globalRank": 4029, "dayRank": 29 },
      { "word": "budget", "zh": "预算", "pos": "business word", "phonetic": "", "globalRank": 4030, "dayRank": 30 },
      { "word": "estimate", "zh": "估算", "pos": "business word", "phonetic": "", "globalRank": 4031, "dayRank": 31 },
      { "word": "quote", "zh": "报价", "pos": "business word", "phonetic": "", "globalRank": 4032, "dayRank": 32 },
      { "word": "invoice", "zh": "发票", "pos": "business word", "phonetic": "", "globalRank": 4033, "dayRank": 33 },
      { "word": "purchase order", "zh": "采购订单", "pos": "business phrase", "phonetic": "", "globalRank": 4034, "dayRank": 34 },
      { "word": "approval", "zh": "批准", "pos": "business word", "phonetic": "", "globalRank": 4035, "dayRank": 35 },
      { "word": "sign-off", "zh": "签字确认", "pos": "business word", "phonetic": "", "globalRank": 4036, "dayRank": 36 },
      { "word": "compliance", "zh": "合规", "pos": "business word", "phonetic": "", "globalRank": 4037, "dayRank": 37 },
      { "word": "legal review", "zh": "法务审核", "pos": "business phrase", "phonetic": "", "globalRank": 4038, "dayRank": 38 },
      { "word": "procurement", "zh": "采购", "pos": "business word", "phonetic": "", "globalRank": 4039, "dayRank": 39 },
      { "word": "vendor", "zh": "供应商", "pos": "business word", "phonetic": "", "globalRank": 4040, "dayRank": 40 },
      { "word": "client", "zh": "客户", "pos": "business word", "phonetic": "", "globalRank": 4041, "dayRank": 41 },
      { "word": "account", "zh": "客户账户", "pos": "business word", "phonetic": "", "globalRank": 4042, "dayRank": 42 },
      { "word": "contract", "zh": "合同", "pos": "business word", "phonetic": "", "globalRank": 4043, "dayRank": 43 },
      { "word": "renewal", "zh": "续约", "pos": "business word", "phonetic": "", "globalRank": 4044, "dayRank": 44 },
      { "word": "churn", "zh": "客户流失", "pos": "business word", "phonetic": "", "globalRank": 4045, "dayRank": 45 },
      { "word": "pipeline", "zh": "销售管道", "pos": "business word", "phonetic": "", "globalRank": 4046, "dayRank": 46 },
      { "word": "lead", "zh": "潜在客户线索", "pos": "business word", "phonetic": "", "globalRank": 4047, "dayRank": 47 },
      { "word": "prospect", "zh": "潜在客户", "pos": "business word", "phonetic": "", "globalRank": 4048, "dayRank": 48 },
      { "word": "opportunity", "zh": "商机", "pos": "business word", "phonetic": "", "globalRank": 4049, "dayRank": 49 },
      { "word": "conversion", "zh": "转化", "pos": "business word", "phonetic": "", "globalRank": 4050, "dayRank": 50 },
      { "word": "retention", "zh": "留存", "pos": "business word", "phonetic": "", "globalRank": 4051, "dayRank": 51 },
      { "word": "onboarding", "zh": "入职导入", "pos": "business word", "phonetic": "", "globalRank": 4052, "dayRank": 52 },
      { "word": "customer success", "zh": "客户成功", "pos": "business phrase", "phonetic": "", "globalRank": 4053, "dayRank": 53 },
      { "word": "support ticket", "zh": "支持工单", "pos": "business phrase", "phonetic": "", "globalRank": 4054, "dayRank": 54 },
      { "word": "escalation", "zh": "升级处理", "pos": "business word", "phonetic": "", "globalRank": 4055, "dayRank": 55 },
      { "word": "SLA", "zh": "服务级别协议", "pos": "business abbreviation", "phonetic": "", "globalRank": 4056, "dayRank": 56 },
      { "word": "incident", "zh": "事故", "pos": "tech business word", "phonetic": "", "globalRank": 4057, "dayRank": 57 },
      { "word": "root cause", "zh": "根因", "pos": "business phrase", "phonetic": "", "globalRank": 4058, "dayRank": 58 },
      { "word": "workaround", "zh": "临时方案", "pos": "business word", "phonetic": "", "globalRank": 4059, "dayRank": 59 },
      { "word": "resolution", "zh": "解决方案", "pos": "business word", "phonetic": "", "globalRank": 4060, "dayRank": 60 },
      { "word": "sprint", "zh": "冲刺", "pos": "tech business word", "phonetic": "", "globalRank": 4061, "dayRank": 61 },
      { "word": "backlog", "zh": "待办列表", "pos": "tech business word", "phonetic": "", "globalRank": 4062, "dayRank": 62 },
      { "word": "ticket", "zh": "工单", "pos": "tech business word", "phonetic": "", "globalRank": 4063, "dayRank": 63 },
      { "word": "bug", "zh": "缺陷", "pos": "tech business word", "phonetic": "", "globalRank": 4064, "dayRank": 64 },
      { "word": "feature", "zh": "功能", "pos": "tech business word", "phonetic": "", "globalRank": 4065, "dayRank": 65 },
      { "word": "release", "zh": "发布", "pos": "tech business word", "phonetic": "", "globalRank": 4066, "dayRank": 66 },
      { "word": "deployment", "zh": "部署", "pos": "tech business word", "phonetic": "", "globalRank": 4067, "dayRank": 67 },
      { "word": "rollback", "zh": "回滚", "pos": "tech business word", "phonetic": "", "globalRank": 4068, "dayRank": 68 },
      { "word": "outage", "zh": "宕机", "pos": "tech business word", "phonetic": "", "globalRank": 4069, "dayRank": 69 },
      { "word": "uptime", "zh": "正常运行时间", "pos": "tech business word", "phonetic": "", "globalRank": 4070, "dayRank": 70 },
      { "word": "dashboard", "zh": "仪表盘", "pos": "tech business word", "phonetic": "", "globalRank": 4071, "dayRank": 71 },
      { "word": "analytics", "zh": "分析数据", "pos": "tech business word", "phonetic": "", "globalRank": 4072, "dayRank": 72 },
      { "word": "metrics", "zh": "指标", "pos": "tech business word", "phonetic": "", "globalRank": 4073, "dayRank": 73 },
      { "word": "data source", "zh": "数据源", "pos": "tech business phrase", "phonetic": "", "globalRank": 4074, "dayRank": 74 },
      { "word": "integration", "zh": "集成", "pos": "tech business word", "phonetic": "", "globalRank": 4075, "dayRank": 75 },
      { "word": "API", "zh": "接口", "pos": "tech abbreviation", "phonetic": "", "globalRank": 4076, "dayRank": 76 },
      { "word": "authentication", "zh": "身份验证", "pos": "tech business word", "phonetic": "", "globalRank": 4077, "dayRank": 77 },
      { "word": "permission", "zh": "权限", "pos": "tech business word", "phonetic": "", "globalRank": 4078, "dayRank": 78 },
      { "word": "access control", "zh": "访问控制", "pos": "tech business phrase", "phonetic": "", "globalRank": 4079, "dayRank": 79 },
      { "word": "security review", "zh": "安全审查", "pos": "tech business phrase", "phonetic": "", "globalRank": 4080, "dayRank": 80 },
      { "word": "Could you clarify", "zh": "能否澄清", "pos": "sentence pattern", "phonetic": "", "globalRank": 4081, "dayRank": 81 },
      { "word": "I'll get back to you", "zh": "我稍后回复", "pos": "sentence pattern", "phonetic": "", "globalRank": 4082, "dayRank": 82 },
      { "word": "Let's align", "zh": "我们对齐一下", "pos": "sentence pattern", "phonetic": "", "globalRank": 4083, "dayRank": 83 },
      { "word": "to be transparent", "zh": "坦白说", "pos": "sentence pattern", "phonetic": "", "globalRank": 4084, "dayRank": 84 },
      { "word": "from my perspective", "zh": "从我的角度", "pos": "sentence pattern", "phonetic": "", "globalRank": 4085, "dayRank": 85 },
      { "word": "quick question", "zh": "快速提问", "pos": "meeting phrase", "phonetic": "", "globalRank": 4086, "dayRank": 86 },
      { "word": "just to confirm", "zh": "只是确认一下", "pos": "sentence pattern", "phonetic": "", "globalRank": 4087, "dayRank": 87 },
      { "word": "moving forward", "zh": "今后", "pos": "business phrase", "phonetic": "", "globalRank": 4088, "dayRank": 88 },
      { "word": "by end of day", "zh": "今日结束前", "pos": "business phrase", "phonetic": "", "globalRank": 4089, "dayRank": 89 },
      { "word": "on track", "zh": "按计划", "pos": "business phrase", "phonetic": "", "globalRank": 4090, "dayRank": 90 },
      { "word": "off track", "zh": "偏离计划", "pos": "business phrase", "phonetic": "", "globalRank": 4091, "dayRank": 91 },
      { "word": "at risk", "zh": "有风险", "pos": "business phrase", "phonetic": "", "globalRank": 4092, "dayRank": 92 },
      { "word": "high-level overview", "zh": "高层概览", "pos": "meeting phrase", "phonetic": "", "globalRank": 4093, "dayRank": 93 },
      { "word": "deep dive", "zh": "深入讨论", "pos": "meeting phrase", "phonetic": "", "globalRank": 4094, "dayRank": 94 },
      { "word": "take this offline", "zh": "会后单独聊", "pos": "meeting phrase", "phonetic": "", "globalRank": 4095, "dayRank": 95 },
      { "word": "loop in", "zh": "拉进沟通", "pos": "business phrasal verb", "phonetic": "", "globalRank": 4096, "dayRank": 96 },
      { "word": "circle back", "zh": "回头跟进", "pos": "business phrasal verb", "phonetic": "", "globalRank": 4097, "dayRank": 97 },
      { "word": "touch base", "zh": "简短沟通", "pos": "business phrasal verb", "phonetic": "", "globalRank": 4098, "dayRank": 98 },
      { "word": "heads-up", "zh": "提醒", "pos": "business word", "phonetic": "", "globalRank": 4099, "dayRank": 99 },
      { "word": "FYI", "zh": "供参考", "pos": "email abbreviation", "phonetic": "", "globalRank": 4100, "dayRank": 100 },
      { "word": "margin", "zh": "利润率", "pos": "finance word", "phonetic": "", "globalRank": 4101, "dayRank": 101 },
      { "word": "revenue", "zh": "收入", "pos": "finance word", "phonetic": "", "globalRank": 4102, "dayRank": 102 },
      { "word": "cost center", "zh": "成本中心", "pos": "finance phrase", "phonetic": "", "globalRank": 4103, "dayRank": 103 },
      { "word": "forecast", "zh": "预测", "pos": "finance word", "phonetic": "", "globalRank": 4104, "dayRank": 104 },
      { "word": "cash flow", "zh": "现金流", "pos": "finance phrase", "phonetic": "", "globalRank": 4105, "dayRank": 105 },
      { "word": "runway", "zh": "可支撑周期", "pos": "startup finance word", "phonetic": "", "globalRank": 4106, "dayRank": 106 },
      { "word": "burn rate", "zh": "烧钱速度", "pos": "startup finance phrase", "phonetic": "", "globalRank": 4107, "dayRank": 107 },
      { "word": "break-even", "zh": "盈亏平衡", "pos": "finance word", "phonetic": "", "globalRank": 4108, "dayRank": 108 },
      { "word": "unit economics", "zh": "单位经济模型", "pos": "finance phrase", "phonetic": "", "globalRank": 4109, "dayRank": 109 },
      { "word": "pricing", "zh": "定价", "pos": "finance word", "phonetic": "", "globalRank": 4110, "dayRank": 110 },
      { "word": "discount", "zh": "折扣", "pos": "finance word", "phonetic": "", "globalRank": 4111, "dayRank": 111 },
      { "word": "refund", "zh": "退款", "pos": "finance word", "phonetic": "", "globalRank": 4112, "dayRank": 112 },
      { "word": "reimbursement", "zh": "报销", "pos": "finance word", "phonetic": "", "globalRank": 4113, "dayRank": 113 },
      { "word": "expense report", "zh": "报销单", "pos": "finance phrase", "phonetic": "", "globalRank": 4114, "dayRank": 114 },
      { "word": "payroll", "zh": "工资发放", "pos": "finance word", "phonetic": "", "globalRank": 4115, "dayRank": 115 },
      { "word": "headcount", "zh": "员工编制", "pos": "business word", "phonetic": "", "globalRank": 4116, "dayRank": 116 },
      { "word": "hiring plan", "zh": "招聘计划", "pos": "business phrase", "phonetic": "", "globalRank": 4117, "dayRank": 117 },
      { "word": "performance review", "zh": "绩效评估", "pos": "business phrase", "phonetic": "", "globalRank": 4118, "dayRank": 118 },
      { "word": "compensation", "zh": "薪酬", "pos": "business word", "phonetic": "", "globalRank": 4119, "dayRank": 119 },
      { "word": "bonus", "zh": "奖金", "pos": "business word", "phonetic": "", "globalRank": 4120, "dayRank": 120 },
      { "word": "time zone", "zh": "时区", "pos": "global work phrase", "phonetic": "", "globalRank": 4121, "dayRank": 121 },
      { "word": "remote team", "zh": "远程团队", "pos": "global work phrase", "phonetic": "", "globalRank": 4122, "dayRank": 122 },
      { "word": "hybrid work", "zh": "混合办公", "pos": "global work phrase", "phonetic": "", "globalRank": 4123, "dayRank": 123 },
      { "word": "office hours", "zh": "答疑时段", "pos": "global work phrase", "phonetic": "", "globalRank": 4124, "dayRank": 124 },
      { "word": "commute delay", "zh": "通勤延误", "pos": "daily work phrase", "phonetic": "", "globalRank": 4125, "dayRank": 125 },
      { "word": "traffic congestion", "zh": "交通拥堵", "pos": "daily work phrase", "phonetic": "", "globalRank": 4126, "dayRank": 126 },
      { "word": "business trip", "zh": "商务出差", "pos": "global work phrase", "phonetic": "", "globalRank": 4127, "dayRank": 127 },
      { "word": "travel policy", "zh": "差旅政策", "pos": "global work phrase", "phonetic": "", "globalRank": 4128, "dayRank": 128 },
      { "word": "itinerary", "zh": "行程", "pos": "global work word", "phonetic": "", "globalRank": 4129, "dayRank": 129 },
      { "word": "reimbursement policy", "zh": "报销政策", "pos": "finance phrase", "phonetic": "", "globalRank": 4130, "dayRank": 130 },
      { "word": "visa status", "zh": "签证状态", "pos": "global work phrase", "phonetic": "", "globalRank": 4131, "dayRank": 131 },
      { "word": "relocation", "zh": "搬迁", "pos": "global work word", "phonetic": "", "globalRank": 4132, "dayRank": 132 },
      { "word": "headquarters", "zh": "总部", "pos": "global work word", "phonetic": "", "globalRank": 4133, "dayRank": 133 },
      { "word": "regional office", "zh": "区域办公室", "pos": "global work phrase", "phonetic": "", "globalRank": 4134, "dayRank": 134 },
      { "word": "offshore team", "zh": "海外团队", "pos": "global work phrase", "phonetic": "", "globalRank": 4135, "dayRank": 135 },
      { "word": "handoff", "zh": "交接", "pos": "business word", "phonetic": "", "globalRank": 4136, "dayRank": 136 },
      { "word": "documentation", "zh": "文档", "pos": "business word", "phonetic": "", "globalRank": 4137, "dayRank": 137 },
      { "word": "knowledge base", "zh": "知识库", "pos": "business phrase", "phonetic": "", "globalRank": 4138, "dayRank": 138 },
      { "word": "training session", "zh": "培训", "pos": "business phrase", "phonetic": "", "globalRank": 4139, "dayRank": 139 },
      { "word": "shadowing", "zh": "跟岗学习", "pos": "business word", "phonetic": "", "globalRank": 4140, "dayRank": 140 },
      { "word": "negotiation", "zh": "谈判", "pos": "business word", "phonetic": "", "globalRank": 4141, "dayRank": 141 },
      { "word": "objection", "zh": "异议", "pos": "business word", "phonetic": "", "globalRank": 4142, "dayRank": 142 },
      { "word": "concession", "zh": "让步", "pos": "business word", "phonetic": "", "globalRank": 4143, "dayRank": 143 },
      { "word": "leverage", "zh": "筹码", "pos": "business word", "phonetic": "", "globalRank": 4144, "dayRank": 144 },
      { "word": "risk tolerance", "zh": "风险承受度", "pos": "business phrase", "phonetic": "", "globalRank": 4145, "dayRank": 145 },
      { "word": "decision maker", "zh": "决策人", "pos": "business phrase", "phonetic": "", "globalRank": 4146, "dayRank": 146 },
      { "word": "gatekeeper", "zh": "守门人", "pos": "business word", "phonetic": "", "globalRank": 4147, "dayRank": 147 },
      { "word": "sponsor", "zh": "发起人", "pos": "business word", "phonetic": "", "globalRank": 4148, "dayRank": 148 },
      { "word": "champion", "zh": "支持者", "pos": "business word", "phonetic": "", "globalRank": 4149, "dayRank": 149 },
      { "word": "buy-in", "zh": "认同支持", "pos": "business word", "phonetic": "", "globalRank": 4150, "dayRank": 150 },
      { "word": "consensus", "zh": "共识", "pos": "business word", "phonetic": "", "globalRank": 4151, "dayRank": 151 },
      { "word": "constraint", "zh": "约束", "pos": "business word", "phonetic": "", "globalRank": 4152, "dayRank": 152 },
      { "word": "assumption", "zh": "假设", "pos": "business word", "phonetic": "", "globalRank": 4153, "dayRank": 153 },
      { "word": "dependency", "zh": "依赖项", "pos": "business word", "phonetic": "", "globalRank": 4154, "dayRank": 154 },
      { "word": "requirement", "zh": "需求", "pos": "business word", "phonetic": "", "globalRank": 4155, "dayRank": 155 },
      { "word": "acceptance criteria", "zh": "验收标准", "pos": "business phrase", "phonetic": "", "globalRank": 4156, "dayRank": 156 },
      { "word": "success metric", "zh": "成功指标", "pos": "business phrase", "phonetic": "", "globalRank": 4157, "dayRank": 157 },
      { "word": "contingency plan", "zh": "应急计划", "pos": "business phrase", "phonetic": "", "globalRank": 4158, "dayRank": 158 },
      { "word": "mitigation", "zh": "缓解措施", "pos": "business word", "phonetic": "", "globalRank": 4159, "dayRank": 159 },
      { "word": "fall-back option", "zh": "备选方案", "pos": "business phrase", "phonetic": "", "globalRank": 4160, "dayRank": 160 },
      { "word": "action-oriented", "zh": "面向行动", "pos": "writing style", "phonetic": "", "globalRank": 4161, "dayRank": 161 },
      { "word": "concise", "zh": "简洁", "pos": "writing style", "phonetic": "", "globalRank": 4162, "dayRank": 162 },
      { "word": "polite but direct", "zh": "礼貌且直接", "pos": "writing style", "phonetic": "", "globalRank": 4163, "dayRank": 163 },
      { "word": "passive voice", "zh": "被动语态", "pos": "grammar term", "phonetic": "", "globalRank": 4164, "dayRank": 164 },
      { "word": "conditional", "zh": "条件句", "pos": "grammar term", "phonetic": "", "globalRank": 4165, "dayRank": 165 },
      { "word": "request phrase", "zh": "请求句式", "pos": "grammar term", "phonetic": "", "globalRank": 4166, "dayRank": 166 },
      { "word": "softener", "zh": "缓和语", "pos": "grammar term", "phonetic": "", "globalRank": 4167, "dayRank": 167 },
      { "word": "modal verb", "zh": "情态动词", "pos": "grammar term", "phonetic": "", "globalRank": 4168, "dayRank": 168 },
      { "word": "conditional clause", "zh": "条件从句", "pos": "grammar term", "phonetic": "", "globalRank": 4169, "dayRank": 169 },
      { "word": "subject line", "zh": "邮件标题", "pos": "email phrase", "phonetic": "", "globalRank": 4170, "dayRank": 170 },
      { "word": "opening line", "zh": "开场句", "pos": "email phrase", "phonetic": "", "globalRank": 4171, "dayRank": 171 },
      { "word": "closing line", "zh": "结尾句", "pos": "email phrase", "phonetic": "", "globalRank": 4172, "dayRank": 172 },
      { "word": "call to action", "zh": "行动号召", "pos": "email phrase", "phonetic": "", "globalRank": 4173, "dayRank": 173 },
      { "word": "due date", "zh": "到期日", "pos": "business phrase", "phonetic": "", "globalRank": 4174, "dayRank": 174 },
      { "word": "owner", "zh": "负责人", "pos": "business word", "phonetic": "", "globalRank": 4175, "dayRank": 175 },
      { "word": "context", "zh": "背景信息", "pos": "business word", "phonetic": "", "globalRank": 4176, "dayRank": 176 },
      { "word": "decision log", "zh": "决策记录", "pos": "business phrase", "phonetic": "", "globalRank": 4177, "dayRank": 177 },
      { "word": "meeting minutes", "zh": "会议纪要", "pos": "business phrase", "phonetic": "", "globalRank": 4178, "dayRank": 178 },
      { "word": "action register", "zh": "行动登记表", "pos": "business phrase", "phonetic": "", "globalRank": 4179, "dayRank": 179 },
      { "word": "shared drive", "zh": "共享盘", "pos": "business phrase", "phonetic": "", "globalRank": 4180, "dayRank": 180 },
      { "word": "accountability", "zh": "问责负责", "pos": "business word", "phonetic": "", "globalRank": 4181, "dayRank": 181 },
      { "word": "initiative", "zh": "主动性", "pos": "business word", "phonetic": "", "globalRank": 4182, "dayRank": 182 },
      { "word": "proactive", "zh": "主动的", "pos": "business word", "phonetic": "", "globalRank": 4183, "dayRank": 183 },
      { "word": "responsive", "zh": "响应及时", "pos": "business word", "phonetic": "", "globalRank": 4184, "dayRank": 184 },
      { "word": "reliable", "zh": "可靠的", "pos": "business word", "phonetic": "", "globalRank": 4185, "dayRank": 185 },
      { "word": "scalable", "zh": "可扩展", "pos": "business word", "phonetic": "", "globalRank": 4186, "dayRank": 186 },
      { "word": "sustainable", "zh": "可持续", "pos": "business word", "phonetic": "", "globalRank": 4187, "dayRank": 187 },
      { "word": "strategic", "zh": "战略性的", "pos": "business word", "phonetic": "", "globalRank": 4188, "dayRank": 188 },
      { "word": "tactical", "zh": "战术性的", "pos": "business word", "phonetic": "", "globalRank": 4189, "dayRank": 189 },
      { "word": "executive summary", "zh": "高管摘要", "pos": "business phrase", "phonetic": "", "globalRank": 4190, "dayRank": 190 },
      { "word": "board meeting", "zh": "董事会会议", "pos": "business phrase", "phonetic": "", "globalRank": 4191, "dayRank": 191 },
      { "word": "investor update", "zh": "投资人更新", "pos": "business phrase", "phonetic": "", "globalRank": 4192, "dayRank": 192 },
      { "word": "partnership", "zh": "伙伴关系", "pos": "business word", "phonetic": "", "globalRank": 4193, "dayRank": 193 },
      { "word": "enterprise client", "zh": "企业客户", "pos": "business phrase", "phonetic": "", "globalRank": 4194, "dayRank": 194 },
      { "word": "go-to-market", "zh": "市场进入策略", "pos": "business phrase", "phonetic": "", "globalRank": 4195, "dayRank": 195 },
      { "word": "competitive analysis", "zh": "竞争分析", "pos": "business phrase", "phonetic": "", "globalRank": 4196, "dayRank": 196 },
      { "word": "value proposition", "zh": "价值主张", "pos": "business phrase", "phonetic": "", "globalRank": 4197, "dayRank": 197 },
      { "word": "customer pain point", "zh": "客户痛点", "pos": "business phrase", "phonetic": "", "globalRank": 4198, "dayRank": 198 },
      { "word": "business outcome", "zh": "商业结果", "pos": "business phrase", "phonetic": "", "globalRank": 4199, "dayRank": 199 },
      { "word": "move forward", "zh": "推进", "pos": "business phrase", "phonetic": "", "globalRank": 4200, "dayRank": 200 }
    ]
  }
];
